version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ~/.kube:/root/.kube:ro # 로컬 Kubeconfig 마운트
    environment:
      - FLASK_ENV=development
