# .github/workflows/deploy.yml

name: Build and Deploy Metric App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write      # GitOps repo에 푸시
      packages: write      # GHCR 푸시
      id-token: write      # (OIDC 인증용 – optional)

    steps:
      - name: Checkout application code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and push Docker image to GHCR
        run: |
          FULL_IMAGE_NAME="ghcr.io/${{ github.repository }}"
          docker build -t $FULL_IMAGE_NAME:$IMAGE_TAG .
          docker push $FULL_IMAGE_NAME:$IMAGE_TAG
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

      - name: Checkout GitOps Configs repository
        uses: actions/checkout@v4
        with:
          repository: devopslabs-jcg/k8s-gitops-configs
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ GitHub Actions에서 자동 제공하는 토큰 사용
          path: k8s-gitops-configs

      - name: Update image tag in Helm values and push
        run: |
          cd k8s-gitops-configs
          sed -i "s|tag: .*|tag: $IMAGE_TAG|g" k8s-app-helm-charts/metric-app/values.yaml

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add k8s-app-helm-charts/metric-app/values.yaml
          git commit -m "Update metric-app image tag to $IMAGE_TAG [skip ci]" || echo "No changes to commit"
          git push
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

