[200~# .github/workflows/deploy.yml (k8s-metric-app 리포지토리)
name: Build and Deploy Metric App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      packages: write 

    steps:
      - name: Checkout application code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Set image tag # <--- CHANGE THIS PART
        id: vars
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV # Use Git commit SHA as the tag. This guarantees uniqueness!

      - name: Build and push Docker image to GHCR
        run: |
          FULL_IMAGE_NAME="ghcr.io/${{ github.repository }}"
          docker build -t $FULL_IMAGE_NAME:$IMAGE_TAG .
          docker push $FULL_IMAGE_NAME:$IMAGE_TAG
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

      - name: Checkout GitOps Configs repository
        uses: actions/checkout@v4
        with:
          repository: devopslabs-jcg/k8s-gitops-configs
          path: k8s-gitops-configs 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update image tag in Helm values and Push
        run: |
          cd k8s-gitops-configs 
          
          # This path is now confirmed correct:
          sed -i "s|tag: .*|tag: ${{ env.IMAGE_TAG }}|g" k8s-app-helm-charts/metric-app/values.yaml 

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add k8s-app-helm-charts/metric-app/values.yaml 
          git commit -m "Update metric-app image tag to ${{ env.IMAGE_TAG }} [skip ci]" 
          git push
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
